### ISSUE TITLE
Change initial coordinates

### ISSUE THREAD

**Issue by AlessioGiambrone** [AlessioGiambrone/15minutes#3]
The webpage starts at Turin; it should start at the center of the used `.pbf`

**Comment by mendaomn** [comment]
It does seem to default to [these coords](https://github.com/AlessioGiambrone/15minutes/blob/master/static/lib/lib.js#L78)

How can you compute the center of the .pdf?

**Comment by AlessioGiambrone** [comment]
I've added the endpoint `/api/boundaries` to the [backend server](https://github.com/AlessioGiambrone/isochrone_server) so that now you can get the extreme coordinates available in the `.pbf`; the central coordinate should be simple to obtain.
